language: node_js
cache:
  directories:
    - node_modules
    - elm-stuff
install:
  - npm install
  - npm run elm-install
node_js:
  - "4.2.4"
  - "5.4"
script:
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
