language: node_js
cache:
  directories:
    - node_modules
    - elm-stuff
install:
  - npm install
  - npm run elm-install
node_js:
  - "4.2.4"
  - "6.1"
script:
  - npm test
sudo: required
dist: trusty
